[sftp]
name = "Enable or disable the sftp access"
command = "/bin/bash scripts/actions/sftp"
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "Enable or disable the sftp access."

    [sftp.arguments]
        [sftp.arguments.with_sftp]
            type = "boolean"
            ask = "Do you need a SFTP access?"
            default = true

[create_database]
name = "Create a database"
command = "/bin/bash scripts/actions/create_database"
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "Create a database or replace a previous one."

[remove_database]
name = "Remove a database"
command = "/bin/bash scripts/actions/remove_database"
# user = "root"  # optional
# cwd = "/" # optional
# accepted_return_codes = [0, 1, 2, 3]  # optional
accepted_return_codes = [0]
description = "Remove the current database."
